# Generated by Django 5.1.6 on 2025-02-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiscalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_propriedade', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_ut', models.IntegerField(blank=True, null=True)),
                ('fiscal_campo', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, choices=[('afonso_claudio', 'Afonso Cláudio'), ('baixo_guandu', 'Baixo Guandu'), ('brejetuba', 'Brejetuba'), ('colatina', 'Colatina'), ('laranja_da_terra', 'Laranja da Terra'), ('santa_teresa', 'Santa Teresa'), ('sao_roque', 'São Roque')], max_length=50, null=True)),
                ('empresa', models.CharField(blank=True, choices=[('inoversa', 'Inoversa'), ('reflore', 'Reflore'), ('genese', 'Gênese'), ('sartori', 'Sartori'), ('vital', 'Vital')], max_length=50, null=True)),
                ('mes_medicao', models.CharField(blank=True, choices=[('JAN_2025', 'JAN 2025'), ('FEV_2025', 'FEV 2025'), ('MAR_2025', 'MAR 2025'), ('ABR_2025', 'ABR 2025'), ('MAI_2025', 'MAI 2025'), ('JUN_2025', 'JUN 2025'), ('JUL_2025', 'JUL 2025'), ('AGO_2025', 'AGO 2025'), ('SET_2025', 'SET 2025'), ('OUT_2025', 'OUT 2025'), ('NOV_2025', 'NOV 2025'), ('DEZ_2025', 'DEZ 2025')], max_length=50, null=True)),
                ('metodo', models.CharField(blank=True, choices=[('Plantio Total', 'Plantio Total'), ('CRN', 'CRN')], max_length=50, null=True)),
                ('id_parcela', models.IntegerField(blank=True, null=True)),
                ('fase', models.CharField(blank=True, choices=[('Implantacao', 'Implantação'), ('Manutencao', 'Manutenção')], max_length=50, null=True)),
                ('atividades', models.CharField(blank=True, choices=[('preparo_mecanizado', 'Preparo mecanizado'), ('alinhamento_marcacao', 'Alinhamento e Marcação'), ('capina_quimica', 'Capina Química'), ('controle_formiga', 'Controle de Formiga'), ('rocada', 'Roçada'), ('bercos_quali_quanti', 'Berços - Qualidade e Quantidade'), ('micro_covas_quali_quanti', 'Micro-covas - Qualidade e Quantidade'), ('calagem_berco', 'Calagem (Berços)'), ('adubacao_plantio', 'Adubação de Plantio'), ('plantio_replantio_mudas', 'Plantio/Replantio de Mudas'), ('semeadura', 'Semeadura Direta'), ('adubacao_cobertura_regenerantes', 'Adubação de Cobertura/Regenerantes'), ('coroamento', 'Coroamento')], max_length=50, null=True)),
                ('area_medicao_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('espacamento', models.CharField(blank=True, max_length=50, null=True)),
                ('nota', models.CharField(blank=True, choices=[('refazer_50', 'Refazer (50%)'), ('razoavel_70', 'Razoável (70%)'), ('adequado_100', 'Adequado (100%)')], max_length=50, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
