# Generated by Django 5.1.6 on 2025-02-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacaobrd_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiscalizacao',
            old_name='fiscal_campo',
            new_name='fiscal_responsavel',
        ),
    ]
