# Generated by Django 5.1.6 on 2025-02-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscalizacaobrd_app", "0004_remove_fiscalizacao_offline_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalizacao",
            name="parcela_t",
            field=models.CharField(
                blank=True,
                choices=[("4x25m", "4x25m"), ("6x10m", "6x10m")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fiscalizacao",
            name="ui",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="fiscalizacao",
            name="fiscal_responsavel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("andre_b", "André B."),
                    ("alan_z", "Alan Z."),
                    ("bruno_l", "Bruno L."),
                    ("cristhiam_r", "Cristhiam R."),
                    ("diego_b", "Diego B."),
                    ("fabrina_n", "Fabrina N."),
                    ("felipe_b", "Felipe B."),
                    ("graciane_c", "Graciane C."),
                    ("joao_b", "João B."),
                    ("kelwin_l", "Kelwin L."),
                    ("rafael_p", "Rafael P."),
                    ("samuel_o", "Samuel O."),
                    ("tercio_p", "Tercio P."),
                    ("thiago_d", "Thiago D."),
                    ("vinicius_d", "Vinicius D."),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
