# Generated by Django 5.1.6 on 2025-02-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscalizacaobrd_app", "0005_fiscalizacao_parcela_t_fiscalizacao_ui_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalizacao",
            name="area_medicao_ha",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
